# content of pytest.ini
[pytest]
addopts = --durations=30 -ra --strict-markers -p no:legacypath
norecursedirs = tests/repos
testpaths = tests
python_files = *.py
pythonpath = repos
filterwarnings =
  ignore::UserWarning
markers =
  regression: tests that fix a reported bug
  disable_clean_stage_check: avoid failing tests if there are leftover files in the stage area
  not_on_windows: mark tests that are skipped on Windows
