name: 'Configure Spack Core'
description: 'Configure Spack Core'
inputs:
  path:
    type: string
    required: false
    default: spack-core
  fetch-depth:
    type: int
    required: false
    default: 1
runs:
  using: "composite"
  steps:
    - name: Setup Base
      if: runner.os == 'Windows'
      shell: bash
      run: mkdir ${{ inputs.path }}

    - name: Setup Base
      if: runner.os != 'Windows'
      shell: bash
      run: mkdir -p ${{ inputs.path }}

    - name: Clone Spack
      shell: bash
      run: |
        . ./.env
        cd ${{ inputs.path }}
        git init
        git remote add origin https://github.com/spack/spack.git
        git fetch --depth ${{ inputs.fetch-depth }} origin ${SPACK_CHECKOUT_VERSION}
        git checkout FETCH_HEAD
        cd -
