name: Checkout Spack Core
description: Checkout Spack Core
inputs:
  path:
    description: Path to checkout Spack repository
    required: false
    default: spack-core
  fetch-depth:
    description: Number of commits to fetch
    required: false
    default: '1'
  builtin:
    description: Path to local clone of the builtin repository
    required: false
    default: ${{ github.workspace }}
runs:
  using: "composite"
  steps:
    - name: Get Spack version
      id: spack-version
      shell: bash
      run: |
        source .ci/env
        echo "version=${SPACK_CHECKOUT_VERSION}" >> $GITHUB_OUTPUT
        echo "gh-repo=${SPACK_CHECKOUT_REPO}" >> $GITHUB_OUTPUT
    - name: Checkout Spack
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        repository: ${{ steps.spack-version.outputs.gh-repo}}
        ref: ${{ steps.spack-version.outputs.version }}
        path: ${{ inputs.path }}
        fetch-depth: ${{ inputs.fetch-depth }}
    - name: Override builtin repository path
      shell: bash
      run: ${{ inputs.path }}/bin/spack repo set --destination "${{ inputs.builtin }}" --scope site builtin
    - name: Spack package repositories
      shell: bash
      run: ${{ inputs.path }}/bin/spack config blame repos
