name: Checkout Spack Core
description: Checkout Spack Core
inputs:
  path:
    description: Path to checkout Spack repository
    required: false
    default: spack-core
  fetch-depth:
    description: Number of commits to fetch
    required: false
    default: '1'
runs:
  using: "composite"
  steps:
    - name: Get Spack version
      id: spack-version
      shell: bash
      run: |
        source .ci/env
        echo "version=${SPACK_CHECKOUT_VERSION}" >> $GITHUB_OUTPUT
    - name: Checkout Spack
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        repository: spack/spack
        ref: ${{ steps.spack-version.outputs.version }}
        path: ${{ inputs.path }}
        fetch-depth: ${{ inputs.fetch-depth }}
