# Copyright Spack Project Developers. See COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack_repo.builtin.build_systems.python import PythonPackage
from spack.package import *


class PyPartialJsonParser(PythonPackage):
    """Parse partial JSON generated by LLM"""

    pypi = "partial-json-parser/partial_json_parser-0.2.1.1.post6.tar.gz"

    license("MIT")

    version("0.2.1.1.post6", sha256="43896b68929678224cbbe4884a6a5fe9251ded4b30b8b7d7eb569e5feea93afc")

    depends_on("py-pdm-backend", type="build")
