# Copyright Spack Project Developers. See COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

import os

from spack_repo.builtin.build_systems.python import PythonPackage

from spack.package import *


class PyOpencvPython(PythonPackage):
    """Wrapper package for OpenCV python bindings."""

    homepage = "https://github.com/opencv/opencv-python"
    # PyPy does not provide the source distribution for all versions
    url = "https://github.com/opencv/opencv-python/archive/refs/tags/88.tar.gz"
    git = "https://github.com/opencv/opencv-python.git"

    license("Apache-2.0")

    version("4.13.0.92", sha256="049293f56726a3ebb01bb7508b973e14e62752a4a0e067ac6af4e371d6aa30d3")
    version("4.12.0.88", sha256="c1cfdef91a45468b1c4404af594e2286ce2bcd343fe318aae287997a395a6c90")

    variant("headless", default=False, description="Build without GUI support")

    depends_on("c", type="build")
    depends_on("cxx", type="build")

    depends_on("py-packaging", type="build")
    depends_on("cmake", type="build")
    depends_on("py-scikit-build@0.14:", type="build")
    # restrictions on setuptools not needed, builds fine with newer versions
    depends_on("py-setuptools", type="build")

    depends_on("python@3.6:", type=("build", "run"))
    # build dependency version restriction from pyproject.toml not needed
    depends_on("py-numpy@2:", type=("build", "run"), when="^python@3.9:")
    depends_on("py-numpy@:2", type=("build", "run"), when="^python@:3.8")

    def setup_build_environment(self, env: EnvironmentModifications) -> None:
        if "+headless" in self.spec:
            env.set("ENABLE_HEADLESS", "ON")

    def patch(self):
        # setup.py's get_and_set_info() expects cv2/version.py to exist.
        # It is normally generated by find_version.py from a git checkout,
        # or pre-included in sdist tarballs. Since we build from a GitHub
        # archive tarball (neither), we must create it ourselves.
        version_dir = os.path.join(self.stage.source_path, "cv2")
        os.makedirs(version_dir, exist_ok=True)
        headless = self.spec.satisfies("+headless")
        with open(os.path.join(version_dir, "version.py"), "w") as f:
            f.write('opencv_version = "{}"\n'.format(self.spec.version))
            f.write("contrib = False\n")
            f.write("headless = {}\n".format(headless))
            f.write("rolling = False\n")
            f.write("ci_build = False\n")

    def url_for_version(self, version):
        url = "https://github.com/opencv/opencv-python/archive/refs/tags/{0}.tar.gz"
        return url.format(version.string.split(".")[-1])
