name: MacOS Spack Build

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-macos
  cancel-in-progress: true

jobs:
  MacOS-Clang:
    name: Apple Clang@17.0 ${{ matrix.name }}
    runs-on: macos-latest
    # env: {CXXFLAGS: "-fno-operator-names -Werror -Wall -Wextra -Wpedantic -Wnull-dereference -Wfloat-conversion -Wshadow -Woverloaded-virtual"}
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: +mpi+openmp
          spec: "erf+mpi+openmp"
        - name: ~mpi+openmp
          spec: "erf~mpi+openmp"
          spec: "erf+mpi+netcdf~particles+openmp"
        - name: +mpi+netcdf~particles+openmp+fft
          spec: "erf+mpi+netcdf~particles+openmp+fft"

    steps:

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Force HTTPS for all GitHub clones (fix submodules)
      shell: bash
      run: |
        git config --global url."https://github.com/".insteadOf "ssh://git@github.com/"
        git config --global url."https://github.com/".insteadOf "git@github.com:"

    - name: Setup Spack
      uses: spack/setup-spack@v2
      with:
        path: ${{ github.workspace }}/spack_install_dir

    - name: Cache Spack downloads
      uses: actions/cache@v4
      with:
        path: |
          ~/.spack/cache
          ${{ github.workspace }}/spack_install_dir/var/spack/cache
        key: spack-cache-${{ runner.os }}-${{ hashFiles('**/package.py', '**/spack.yaml') }}
        restore-keys: |
          spack-cache-${{ runner.os }}-

    - name: Build ERF (${{ matrix.spec }})
      shell: bash
      run: |
        set -euxo pipefail
        echo ${{ github.workspace }}
        echo ${{ runner.workspace }}
        . ${{ github.workspace }}/spack_install_dir/share/spack/setup-env.sh
        spack repo add --name erf_git https://github.com/larenspear/spack-packages.git
        spack env create -d ./.env
        spack -e ./.env add ${{ matrix.spec }}
        spack -e ./.env concretize -f
        spack -e ./.env install -j $(sysctl -n hw.ncpu)
