name: prechecks

on:
  workflow_call:
    inputs:
      with_packages:
        required: true
        type: string

concurrency:
  group: prechecks-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}
  cancel-in-progress: true


jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: Noop
        run: echo "ok"